### ISSUE TITLE
Exception: There is no such day in this month!

### ISSUE THREAD

**Issue by PetzoldMartin** [CallMeFoxie/Calendar#10]
Get this error in Regular Steps

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SFRCore (SolarFluxReborn_1.10.2-1.4r.jar)
  IC2core (industrialcraft-2-2.6.69-ex110.jar)
  StreamsCoreMod (Streams-1.9.4-0.2.1.jar)
  BetterSleeping Core (BetterSleeping-1.10.2-2.0-gamma-11.jar)
  FarseekCoreMod (Farseek-1.9.4-1.1.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  BetterFoliageLoader (BetterFoliage-MC1.10-2.1.1.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  MalisisCorePlugin (malisiscore-1.9.4-4.1.1.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 23/09/16 17:21
Description: Exception in server tick loop

java.lang.IllegalArgumentException: There is no such day in this month!
    at foxie.calendar.implementation.CalendarImpl.setDay(CalendarImpl.java:99)
    at foxie.bettersleeping.modules.TirednessModule.onWorldSleepPre(TirednessModule.java:177)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_39_TirednessModule_onWorldSleepPre_Pre.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at foxie.bettersleeping.core.BSEvents.getSleepingTime(BSEvents.java:32)
    at foxie.bettersleeping.modules.TirednessModule.onWorldTick(TirednessModule.java:153)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_41_TirednessModule_onWorldTick_WorldTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:282)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:694)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:463)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Linux (amd64) version 3.14.32-xxxx-std-ipv6-64-hz1000
    Java Version: 1.8.0_92, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 274330024 bytes (261 MB) / 1232973824 bytes (1175 MB) up to 2075918336 bytes (1979 MB)
    JVM Flags: 20 total; -Xincgc -XX:+UseParNewGC -XX:MaxPermSize=256M -XX:NewRatio=2 -XX:CMSFullGCsBeforeCompaction=1 -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=2048 -XX:+CMSParallelRemarkEnabled -XX:+DisableExplicitGC -Xnoclassgc -Xoss4M -Xss4M -XX:+UseFastAccessorMethods -XX:CMSInitiatingOccupancyFraction=90 -XX:UseSSE=4 -XX:+UseCMSCompactAtFullCollection -XX:ParallelGCThreads=4 -XX:+AggressiveOpts -Xmx2048M -Xms512M
    IntCache: cache: 0, tcache: 0, allocated: 9, tallocated: 61
    FML: MCP 9.32 Powered by Forge 12.18.1.2092 113 mods loaded, 113 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2092-universal.jar) 
    UCHIJAAAA   Forge{12.18.1.2092} [Minecraft Forge](forge-1.10.2-12.18.1.2092-universal.jar) 
    UCHIJAAAA   bettersleepingcore{2.0} [Better Sleeping 2 Core](minecraft.jar) 
    UCHIJAAAA   OpenComputers|Core{1.6.0.3-rc.1} [OpenComputers (Core)](minecraft.jar) 
    UCHIJAAAA   movillages{1.5.2} [Mo' Villages]([1.9.4]Mo' Villages-1.5.2.jar) 
    UCHIJAAAA   ForgeEndertech{1.1.3.0} [Forge Endertech](ForgeEndertech-1.10.2-1.1.3.0.jar) 
    UCHIJAAAA   AdChimneys{1.10.2-1.1.3.1} [Advanced Chimneys](AdChimneys-1.10.2-1.1.3.1.jar) 
    UCHIJAAAA   CookingPlus{0.8.8} [The Agricultural Revolution](Agricultural Revolution-1.10.2-0.8.8.jar) 
    UCHIJAAAA   agriculturalexpansion{r-1.2.0} [Agricultural Expansion](AgriculturalExpansion[1.9.4][1.10.2]-r1.2.1.jar) 
    UCHIJAAAA   aquaculture{1.4.0} [Aquaculture](Aquaculture-1.10.2-1.4.0.28.jar) 
    UCHIJAAAA   thedragoncore{1.1.0} [TheDragonCore](thedragoncore-1.1.0.jar) 
    UCHIJAAAA   armorplus{1.10.2-6.0.9.2} [ArmorPlus](armorplus-1.10.2-6.0.9.2.jar) 
    UCHIJAAAA   backpack{3.0.1} [Backpack](backpack-3.0.1-1.10.2.jar) 
    UCHIJAAAA   Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
    UCHIJAAAA   bdlib{1.12.2.8} [BD Lib](bdlib-1.12.2.8-mc1.10.2.jar) 
    UCHIJAAAA   mantle{1.10.2-1.0.0.jenkins170} [Mantle](Mantle-1.10.2-1.0.0.jar) 
    UCHIJAAAA   tconstruct{1.10.2-2.5.2.jenkins352} [Tinkers' Construct](TConstruct-1.10.2-2.5.2.jar) 
    UCHIJAAAA   betterwithmods{0.11 Beta hotfix 2} [Better With Mods](Better With Mods-0.11-1.10.2-hotfix2.jar) 
    UCHIJAAAA   BetterAchievements{0.3.0.30} [Better Achievements](BetterAchievements-1.10.2-0.3.0.30.jar) 
    UCHIJAAAA   betteragriculture{0.16} [Better Agriculture](BetterAgriculture_%28MC-1.10%29-0.16.jar) 
    UCHIJAAAA   BetterFoliage{2.1.1} [Better Foliage](BetterFoliage-MC1.10-2.1.1.jar) 
    UCHIJAAAA   calendarapi{1.5} [CalendarAPI](Calendar-1.10.2-1.5-10.jar) 
    UCHIJAAAA   foxielib{1.0} [FoxieLib](FoxieLib-1.10.2-1.0-9.jar) 
    UCHIJAAAA   bettersleeping{2.0-gamma} [Better Sleeping](BetterSleeping-1.10.2-2.0-gamma-11.jar) 
    UCHIJAAAA   bookshelfapi{3.3.0} [Bookshelf](Bookshelf-API-1.10.2-3.3.0.jar) 
    UCHIJAAAA   Botania{r1.9-323} [Botania](Botania r1.9-323.jar) 
    UCHIJAAAA   canijoinnow{@VERSION@} [Can I Join Now?](CanIJoinNow-1.10-1.0-4.jar) 
    UCHIJAAAA   Chameleon{1.10-2.1.7} [Chameleon](Chameleon-1.10-2.1.7.jar) 
    UCHIJAAAA   ChestTransporter{2.5.2} [Chest Transporter](ChestTransporter-1.10.2-2.5.2.jar) 
    UCHIJAAAA   chisel{MC1.9.4-0.0.6.46} [Chisel](Chisel-MC1.9.4-0.0.6.46.jar) 
    UCHIJAAAA   mcmultipart{1.2.1} [MCMultiPart](MCMultiPart-1.2.1-universal.jar) 
    UCHIJAAAA   chiselsandbits{12.1} [Chisels & Bits](chiselsandbits-12.1.jar) 
    UCHIJAAAA   clockhud{1.3.2} [Clock HUD](ClockHUD-1.10.2-1.3.2.jar) 
    UCHIJAAAA   IC2{2.6.69-ex110} [IndustrialCraft 2](industrialcraft-2-2.6.69-ex110.jar) 
    UCHIJAAAA   CompactSolars{5.0.4.328} [Compact Solar Arrays](CompactSolars-1.10.2-5.0.4.328-universal.jar) 
    UCHIJAAAA   conquest{0.0.1} [Conquest Reforged](conquest_reforged_MOD.jar) 
    UCHIJAAAA   cookingforblockheads{4.2.15} [Cooking for Blockheads](CookingForBlockheads_1.10.2-4.2.15.jar) 
    UCHIJAAAA   coralreef{1.0} [Coral Reef](CoralReef-1.2.jar) 
    UCHIJAAAA   covers{0.3.0.6} [Simple Covers](covers-0.3.0.6-mc1.10.2.jar) 
    UCHIJAAAA   MineTweaker3{3.0.11} [MineTweaker 3](CraftTweaker-1.10.2-3.0.11.jar) 
    UCHIJAAAA   ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.10.2-alpha-1.0.1.jar) 
    UCHIJAAAA   JEI{3.10.0.267} [Just Enough Items](jei_1.10.2-3.10.0.267.jar) 
    UCHIJAAAA   forestry{5.2.12.257} [Forestry](forestry_1.10.2-5.2.12.257.jar) 
    UCHIJAAAA   ElecCore{1.5.311} [ElecCore](ElecCore-1.9.4-1.5.311.jar) 
    UCHIJAAAA   OpenComputers{1.6.0.3-rc.1} [OpenComputers](OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar) 
    UCHIJAAAA   deepresonance{1.2.4} [DeepResonance](deepresonance-1.10-1.2.4.jar) 
    UCHIJAAAA   elementaldimensions{0.0.3} [Elemental Dimensions](elementaldimensions-0.0.3.jar) 
    UCHIJAAAA   enderutilities{0.6.5} [Ender Utilities](enderutilities-1.10.2-0.6.5.jar) 
    UCHIJAAAA   excore{1.6.2} [EXCore](Excore-1.6.2-1.10.2.jar) 
    UCHIJAAAA   exnihiloomnia{1.1.0} [Ex Nihilo Omnia](exnihiloomnia-1.1.0.jar) 
    UCHIJAAAA   golems{6.02} [Extra Golems](ExtraGolems[1.10.2]-6.02.jar) 
    UCHIJAAAA   shadowmc{3.4.5} [ShadowMC](ShadowMC-1.10.2-3.4.5.jar) 
    UCHIJAAAA   ExtraRails{1.1.1} [Extra Rails](ExtraRails-1.10.2-1.1.1.jar) 
    UCHIJAAAA   zerocore{1.10.2-0.0.8.0} [Zero CORE](zerocore-1.10.2-0.0.8.0.jar) 
    UCHIJAAAA   bigreactors{0.4.5.15} [Extreme Reactors](ExtremeReactors-1.10.2-0.4.5.15.jar) 
    UCHIJAAAA   Farseek{1.9.4} [Farseek](Farseek-1.9.4-1.1.jar) 
    UCHIJAAAA   fastleafdecay{v11} [Fast Leaf Decay](FastLeafDecay-v11.jar) 
    UCHIJAAAA   FloodLights{1.2.7-145} [Flood Lights](FloodLights-1.9.4-1.2.7-145.jar) 
    UCHIJAAAA   fluxducts{1.0.4} [Flux Ducts](fluxducts-mc1.9.4-1.0.4.jar) 
    UCHIJAAAA   FEI{1.0.15} [Forever Enough Items](ForeverEnoughItems-1.0.15-1.10.2.jar) 
    UCHIJAAAA   gendustry{1.6.4.17} [GenDustry](gendustry-1.6.4.17-mc1.10.2.jar) 
    UCHIJAAAA   pressure{1.3.1.11} [Pressure Pipes](pressure-1.3.1.11-mc1.10.2.jar) 
    UCHIJAAAA   advgenerators{0.9.20.10} [Advanced Generators](generators-0.9.20.10-mc1.10.2.jar) 
    UCHIJAAAA   exp{1.1} [Exp Seedling Mod](GiacomosExperienceSeedling1.9.4-1.1.jar) 
    UCHIJAAAA   fishing{1.4.4} [Fishing Net Mod](GiacomosFishingNet1.10.2-1.4.4.jar) 
    UCHIJAAAA   giacomosfoundry{1.3.5} [Giacomo's Foundry](GiacomosFoundry1.10.2-1.3.5.jar) 
    UCHIJAAAA   giacomostravelogue{1.01} [Giacomo’s Travelogue](GiacomosTravelogue1.10.2-1.01.jar) 
    UCHIJAAAA   glasscraftmod{1.0} [Glasscraft](Glasscraftmod v1.0 - MC1.10.2 Forge.jar) 
    UCHIJAAAA   gravestone{1.5.6} [Gravestone](GraveStone Mod 1.5.6.jar) 
    UCHIJAAAA   HoloInventory{2.0.2.136} [HoloInventory](HoloInventory-1.9.4-2.0.2.136.jar) 
    UCHIJAAAA   hopperducts{1.4.8} [Hopper Ducts](hopperducts-mc1.9.4-1.4.8.jar) 
    UCHIJAAAA   immcraft{1.1.7} [Immersive Craft](immcraft-1.9.4-1.1.7.jar) 
    UCHIJAAAA   imc{1.12.1} [Improving Minecraft](Improving Minecraft-1.12.1.jar) 
    UCHIJAAAA   inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks](InventoryTweaks-1.61-58.jar) 
    UCHIJAAAA   jacb{1.0.6} [JACB](JACB-1.10.2-1.0.6.jar) 
    UCHIJAAAA   JEFB{1.0.3} [Just Enough Forestry Bees](jefb_1.10.2-1.0.3.jar) 
    UCHIJAAAA   jeibees{0.9.0.1} [JEI Bees](jeibees-0.9.0.1-mc1.10.2.jar) 
    UCHIJAAAA   levelup{${version}} [Level Up!](LevelUp!-0.12-1.10.2.jar) 
    UCHIJAAAA   malisiscore{1.9.4-4.1.1} [MalisisCore](malisiscore-1.9.4-4.1.1.jar) 
    UCHIJAAAA   malisisblocks{1.9.4-4.0.1} [Malisis Blocks](malisisblocks-1.9.4-4.0.1.jar) 
    UCHIJAAAA   malisisdoors{1.9.4-5.0.4} [MalisisDoors](malisisdoors-1.9.4-5.0.4.jar) 
    UCHIJAAAA   minecolonies{1.10.2-0.4.907} [MineColonies](minecolonies-universal-1.10.2-0.4.907.jar) 
    UCHIJAAAA   missing_pieces{4.0.2} [Missing Pieces](missing_pieces-1.10.2-4.0.2.jar) 
    UCHIJAAAA   morebees{1.10.2-1.1.3} [More Bees](morebees-1.10.2-1.1.3.jar) 
    UCHIJAAAA   morematerials{1.10.2-1.9.20160723.0} [More Materials](morematerials-1.10.2-1.9.20160723.0.jar) 
    UCHIJAAAA   mychunkloader{1.9.4-1.10.2-03} [My Chunk Loader](Mychunkloader-1.9.4-1.10.2-03.jar) 
    UCHIJAAAA   netherportalfix{1.0} [Nether Portal Fix](netherportalfix-mc1.9.4-4.0.1.jar) 
    UCHIJAAAA   ninjagear{1.10.2-0.0.3} [NinjaGear](ninjagear-0.0.3.jar) 
    UCHIJAAAA   fodc{1.9.1} [Ore Dictionary Converter](OreDictionaryConverter-1.9.1.jar) 
    UCHIJAAAA   placemod{3.8} [Placemod](placemod-3.8-1.10.2.jar) 
    UCHIJAAAA   progressiveautomation{1.6.51} [Progressive Automation](ProgressiveAutomation-1.10.2-1.6.51.jar) 
    UCHIJAAAA   redstonepaste{1.7.4} [Redstone Paste](redstonepaste-mc1.9.4-1.7.4.jar) 
    UCHIJAAAA   StorageDrawers{1.10.2-3.2.7} [Storage Drawers](StorageDrawers-1.10.2-3.2.7.jar) 
    UCHIJAAAA   refinedstorage{1.0.5} [Refined Storage](refinedstorage-1.0.5.jar) 
    UCHIJAAAA   regrowableleaves{1.10.2-3.1.2} [Regrowable Leaves](regrowableleaves-1.10.2-3.1.2.jar) 
    UCHIJAAAA   reptilemod{3.5.2} [Reptile Mod](reptilemod-1.10.2-3.5.2-58.jar) 
    UCHIJAAAA   rftools{5.24} [RFTools](rftools-1.10-5.24.jar) 
    UCHIJAAAA   rftoolscontrol{1.1.0} [RFTools Control](rftoolsctrl-1.10-1.1.0.jar) 
    UCHIJAAAA   rftoolsdim{4.30beta50} [RFTools Dimensions](rftoolsdim-1.10-4.30beta50.jar) 
    UCHIJAAAA   RTG{1.10.2} [Realistic Terrain Generation](RTG-1.10.2-4.1.1.2-snapshot-5.jar) 
    UCHIJAAAA   showcasemod{0.2} [Showcase Mod](showcasemod-0.3-1.10.2.jar) 
    UCHIJAAAA   SimpleUpgrades{2.1.7} [SimpleUpgrades](simpleupgrades-1.10.2-2.1.7-release.jar) 
    UCHIJAAAA   simplycaterpillar{6.0.1.22} [Simply Caterpillar](SimplyCaterpillar-Forge-6.0.1.22.jar) 
    UCHIJAAAA   slug{1.0A} [Slugs EU and RF converters](Slugs Converters.jar) 
    UCHIJAAAA   SolarFluxReborn{1.4r} [Solar Flux Reborn](SolarFluxReborn_1.10.2-1.4r.jar) 
    UCHIJAAAA   Streams{1.9.4} [Streams](Streams-1.9.4-0.2.1.jar) 
    UCHIJAAAA   teletoro{1.10.2-19} [TeleToro](teletoro-1.10.2-19.jar) 
    UCHIJAAAA   treechopper{1.0.4} [Tree Chopper](TreeChopper-1.0.4.jar) 
    UCHIJAAAA   vc{v2.0.0a-mc1.10.2} [ViesCraft](ViesCraft-2.0.0a-mc1.10.2.jar) 
    UCHIJAAAA   villagebox{0.5.0} [Village Box](villagebox-1.10.2-0.5.0.jar) 
    UCHIJAAAA   Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UCHIJAAAA   waterstrainer{1.3.0} [Water Strainer](WaterStrainer-1.9.4-1.3.0.jar) 
    Loaded coremods (and transformers): 
SFRCore (SolarFluxReborn_1.10.2-1.4r.jar)
  com.mrdimka.solarfluxreborn.core.SFRSerializedTransformer
IC2core (industrialcraft-2-2.6.69-ex110.jar)

StreamsCoreMod (Streams-1.9.4-0.2.1.jar)
  streams.core.StreamsClassTransformer
BetterSleeping Core (BetterSleeping-1.10.2-2.0-gamma-11.jar)
  foxie.bettersleeping.asm.PatchCollection
FarseekCoreMod (Farseek-1.9.4-1.1.jar)
  farseek.core.FarseekClassTransformer
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
BetterFoliageLoader (BetterFoliage-MC1.10-2.1.1.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  li.cil.oc.common.asm.ClassTransformer
MalisisCorePlugin (malisiscore-1.9.4-4.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerHarvestTools (Enabled/Forced)
        - TinkerMeleeWeapons (Enabled/Forced)
        - TinkerRangedWeapons (Enabled/Forced)
        - TinkerModifiers (Enabled/Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - TinkerModelRegister (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - WailaIntegration (Enabled/Not Forced)

```
List of loaded APIs: 
    * Baubles|API (1.1.1.0) from Baubles-1.9.4-1.2.1.0.jar
    * BetterAchievements|API (0.3.0.30) from BetterAchievements-1.10.2-0.3.0.30.jar
    * bettersleeping|api (3.0) from BetterSleeping-1.10.2-2.0-gamma-11.jar
    * BetterWithModsAPI (Beta 0.6) from Better With Mods-0.11-1.10.2-hotfix2.jar
    * BotaniaAPI (80) from Botania r1.9-323.jar
    * calendarapi|api (1.5) from Calendar-1.10.2-1.5-10.jar
    * ChiselAPI (0.0.1) from Chisel-MC1.9.4-0.0.6.46.jar
    * ChiselAPI|Carving (0.0.1) from Chisel-MC1.9.4-0.0.6.46.jar
    * ChiselsAndBitsAPI (11.7.0) from chiselsandbits-12.1.jar
    * CoFHAPI (1.8.9R1.2.0B1) from extrautils2-1.10.2-alpha-1.0.1.jar
    * CoFHAPI|block (1.8.9R1.2.0B1) from fluxducts-mc1.9.4-1.0.4.jar
    * CoFHAPI|core (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.0.jar
    * CoFHAPI|energy (1.8.9R1.2.0B1) from extrautils2-1.10.2-alpha-1.0.1.jar
    * CoFHAPI|inventory (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.0.jar
    * CoFHAPI|item (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.0.jar
    * CoFHAPI|tileentity (1.8.9R1.2.0B1) from fluxducts-mc1.9.4-1.0.4.jar
    * CoFHAPI|transport (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.0.jar
    * ComputerCraft|API (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
    * ComputerCraft|API|FileSystem (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
    * ComputerCraft|API|Lua (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
    * ComputerCraft|API|Media (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
    * ComputerCraft|API|Peripheral (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
    * ComputerCraft|API|Permissions (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
    * ComputerCraft|API|Redstone (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
    * ComputerCraft|API|Turtle (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
    * DR-API (1.0.4-Beta) from deepresonance-1.10-1.2.4.jar
    * ElecCore|Abilities (#API_VER#) from ElecCore-1.9.4-1.5.311.jar
    * ForestryAPI|apiculture (5.0.0) from forestry_1.10.2-5.2.12.257.jar
    * ForestryAPI|arboriculture (4.2.1) from forestry_1.10.2-5.2.12.257.jar
    * ForestryAPI|circuits (3.1.0) from forestry_1.10.2-5.2.12.257.jar
    * ForestryAPI|climate (2.1.0) from forestry_1.10.2-5.2.12.257.jar
    * ForestryAPI|core (5.0.0) from forestry_1.10.2-5.2.12.257.jar
    * ForestryAPI|farming (2.1.0) from forestry_1.10.2-5.2.12.257.jar
    * ForestryAPI|food (1.1.0) from forestry_1.10.2-5.2.12.257.jar
    * ForestryAPI|fuels (3.0.0) from forestry_1.10.2-5.2.12.257.jar
    * ForestryAPI|genetics (4.7.1) from forestry_1.10.2-5.2.12.257.jar
    * ForestryAPI|greenhouse (5.2.0) from forestry_1.10.2-5.2.12.257.jar
    * ForestryAPI|hives (4.1.0) from forestry_1.10.2-5.2.12.257.jar
    * ForestryAPI|lepidopterology (1.3.0) from forestry_1.10.2-5.2.12.257.jar
    * ForestryAPI|mail (3.0.0) from forestry_1.10.2-5.2.12.257.jar
    * ForestryAPI|multiblock (3.0.0) from forestry_1.10.2-5.2.12.257.jar
    * ForestryAPI|recipes (5.4.0) from forestry_1.10.2-5.2.12.257.jar
    * ForestryAPI|storage (5.0.0) from forestry_1.10.2-5.2.12.257.jar
    * ForestryAPI|world (2.1.0) from forestry_1.10.2-5.2.12.257.jar
    * gendustryAPI (2.3.0) from gendustry-1.6.4.17-mc1.10.2.jar
    * IC2API (1.0) from Slugs Converters.jar
    * jeresources|API (0.5.1.56) from JustEnoughResources-1.10.2-0.5.1.56.jar
    * JustEnoughItemsAPI (4.3.0) from jei_1.10.2-3.10.0.267.jar
    * MapWriterApi (1.1.0) from MapWriter-1.10.2-2.6.19.jar
    * McJtyLib (1.10-2.1.2) from mcjtylib-1.10-2.1.2.jar
    * NinjaGearAPI (1.0) from ninjagear-0.0.3.jar
    * OpenComputersAPI|Component (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
    * OpenComputersAPI|Core (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
    * OpenComputersAPI|Driver (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
    * OpenComputersAPI|Driver|Item (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
    * OpenComputersAPI|Event (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
    * OpenComputersAPI|FileSystem (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
    * OpenComputersAPI|Internal (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
    * OpenComputersAPI|Machine (6.0.0-alpha) from zerocore-1.10.2-0.0.8.0.jar
    * OpenComputersAPI|Manual (6.0.0-alpha) from zerocore-1.10.2-0.0.8.0.jar
    * OpenComputersAPI|Network (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
    * OpenComputersAPI|Prefab (6.0.0-alpha) from zerocore-1.10.2-0.0.8.0.jar
    * pressureAPI (1.3.1.11) from pressure-1.3.1.11-mc1.10.2.jar
    * StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * StorageDrawersAPI|inventory (1.7.10-1.2.0) from refinedstorage-1.0.5.jar
    * StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
    * zerocore|API|multiblock (1.9.4-0.0.1) from zerocore-1.10.2-0.0.8.0.jar
    * zerocore|API|multiblock|rectangular (1.9.4-0.0.1) from zerocore-1.10.2-0.0.8.0.jar
    * zerocore|API|multiblock|validation (1.9.4-0.0.1) from zerocore-1.10.2-0.0.8.0.jar
Profiler Position: N/A (disabled)
Player Count: 1 / 5; [EntityPlayerMP['Aismael'/262, l='Second', x=502.50, y=68.00, z=-286.50]]
Is Modded: Definitely; Server brand changed to 'fml,forge'
Type: Dedicated Server (map_server.txt)
```

**Comment by CallMeFoxie** [comment]
Hi, can you, please, do /date command and tell me what date it is?

I presume that you have default config of CalendarAPI?

**Comment by PetzoldMartin** [comment]
Yes we Used the original Config Data and the date is
and one Date for Crashing was for example 30.6.04

**Comment by CallMeFoxie** [comment]
Should be fixed with https://github.com/CallMeFoxie/BetterSleeping2/commit/eb03d9dd4783d8dcbae330c7f84c5ac8c9251998
