### ISSUE TITLE
How do I set the date??

### ISSUE THREAD

**Issue by ghost** [CallMeFoxie/Calendar#11]
I tried everything with /date set and it always says: There is no such day in a year!
Please help!! Ugh, why is there no explanation for the mod??

**Comment by PitchBright** [comment]
It's not a mod. It's an API. Its purpose is to let other mods, synchronize with one another, and agree upon a common date.

**Comment by ghost** [comment]
oh... i have been finding a season mod for 1.10.2 and i thought that calendar api was the season mod there and thanks for telling me that
NOW WHERE DO I FIND A DYNAMIC MINECRAFT SEASON MOD FOR 1.10.2?!

**Comment by CallMeFoxie** [comment]
sadly not here... I might be working on something but not going to be released anytime soon.
