### ISSUE TITLE
Crash? Might be Dynamic Surroundings, might be C API [Solved] Caused by Stellar Sky

### ISSUE THREAD

**Issue by Drakoflame** [CallMeFoxie/Calendar#9]
I'm not sure who to report this to, so I'm sending it to you, and to OreCruncher

http://pastebin.com/8kP4JCSW

Basically, WITH Calendar API V1.7.10-1.0-4, the game crashes asking for Calendar API version 1.1,2.0
Without? perfectly fine, booted up like normal....

**Comment by Abastro** [comment]
Its calendar api. Currently Stellar sky dows not provide compatibility with calendar api.

**Comment by Drakoflame** [comment]
@Abastro Thanks for letting me know, I figured that it might have been SS. Your working on integrating the API right? It would help very much with Dynamic Surroundings and the way that SS lets you change day/night cycles
